### ISSUE TITLE
onSubmitEditing Not working

### ISSUE THREAD

**Issue by renganatha10** [lukaspawlik/react-native-dismissable-numeric-keyboard#1]
When i click the done button on numeric keyboard,  onSubmitEditing function is not triggered. Does this lib has that functionality ?

**Comment by ngnclht1102** [comment]
hi @lukaspawlik Problem happend with me too, the onSubmitEditing callback not work.

**Comment by lukaspawlik** [comment]
Hi @rengasahusoft and @ngnclht1102 

Sorry for really long response.

This plugin initially didn't need to listen for `onSubmitEditing` event. I'll take a look at this soon and I'll see what can I do here.

**Comment by lukaspawlik** [comment]
@ngnclht1102 @rengasahusoft I've prepared new branch you can test on your projects.

Please replace current dependency in package.json with

"react-native-dismissable-numeric-keyboard": "git+https://github.com/lukaspawlik/react-native-dismissable-numeric-keyboard.git#feature/emit-on-submit-editing-event"

Please let me know if it works (I tested it and it works correctly however I'd like to hear your feedback) and I'll merge it to master and release on npmjs.org

**Comment by lukaspawlik** [comment]
@ngnclht1102 @rengasahusoft I know it's slow process :) but I am gonna merge this into the master next week :) - JFYI

**Comment by lukaspawlik** [comment]
This has been released.
