### ISSUE TITLE
Adding  returnKeyType="done" to TextInput with Numeric Keyboard causes app to crash

### ISSUE THREAD

**Issue by jlcrow** [lukaspawlik/react-native-dismissable-numeric-keyboard#3]
react-native: 0.46.1
react: 16.0.0-alpha.12
react-native-dismissable-numeric-keyboard: 0.0.2
Adding property

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RCTTextField setInputAccessoryView:]: unrecognized selector sent to instance 0x7f8adf11f0e0'

**Comment by kmcrawford** [comment]
I see this happening on the following line:
 ((UITextField *)view).inputAccessoryView = toolbar;

**Comment by simplenotezy** [comment]
I have same issue

**Comment by adeb6600** [comment]
i have the same issue

**Comment by lukaspawlik** [comment]
This module is not compatible with React Native 0.46.1 (and anything above 0.39). I am tagging this as enhancement as it's high time to upgrade this lib a bit.

**Comment by jlcrow** [comment]
I believe React 0.47 and above includes this functionality
